language: python
jobs:
    include:
        - name: "Xenial Linux"
          python:
            - "3.6"
            - "3.7"
        - name: "macOS"
          os: osx
          osx_image: xcoode11.2
          language: shell
        - name: "Windows"
          os: windows
          language: shell
          before_install:
              - choco install python --version 3.7.0
              - python -m pip install --upgrade pip
          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
    - pip install -r requirements.txt
    - pip install -r tests/requirements.txt
script:
    - pytest --ignore=pybind11
